version: "3"

services:
  frontend:
    build: frontend-streamlit
    ports:
      - 8501:8501
    depends_on:
      - backend
    volumes:
        - ./frontend-streamlit:/streamlit_app
        - ./storage:/storage
  backend:
    build: .
    ports:
      - 8000:8000
    volumes:
        - ./app:/app
        - ./storage:/storage