wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.8.12
    start_time: 1652364748
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      2:
      - 5
      - 6
      - 53
      - 55
      4: 3.8.12
      5: 0.12.16
      8:
      - 1
      - 2
      - 4
      - 5
